### PR TITLE
Remove $setup as array in Gacela::bootstrap

### PR DESCRIPTION
**Pull request by JesusValera**
## 📚 Description

Remove deprecated array config in `Gacela::bootstrap`.

### CODE REVIEW

**Review by Chemaclass — APPROVED** [review]

**Comment by Tito-Kati** [comment]
Are you going to remove support for the classic array configuration so soon?

**Comment by Chemaclass** [comment]
@Tito-Kati next release would be plan in 3 or 4 week... Isn't that enough? Or should we keep a few versions in between? What are your thoughts about it?

**Comment by Tito-Kati** [comment]
@Chemaclass In other projects, they wait until major releases to remove all deprecations.

Although your project is still young, I guess it's fine. Write some nice upgrade guide for this.

**Review by Tito-Kati — APPROVED** [review]

**Comment by Chemaclass** [comment]
This wont be merged in the next release 0.16, BUT on the next one 0.17.

**Pull request merged**
