### PR TITLE
Enhancement: Keep packages sorted in `composer.json`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] keeps packages sorted in `composer.json`

💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.

### CODE REVIEW

**Review by Chemaclass — APPROVED** [review]
Thanks!

**Comment by localheinz** [comment]
@Chemaclass 

You may need to update #308 then, where packages currently are not sorted in `composer.json`.

**Review by JesusValera — APPROVED** [review]
I didn't know this one, interesting 👯

**Comment by localheinz** [comment]
Thank you, @Chemaclass and @JesusValera!

**Pull request merged**
